import java.util.*;
import static java.lang.Math.log;
import static jdk.internal.org.jline.utils.AttributedStringBuilder.append;

public class HW7 {
    public static void main(String[] args) {
//(a) Suppose we need to store the result of the mathematical calculation log(4096)/ log(2) in an
//integer variable called x. Write a line of code to do this.
        double x = log(4096)/log(2);
        System.out.println(x);
//(b) One way to generate a random lowercase letter is to generate a random number from 97 to 122
//(the letter’s ASCII code) and then store the result in a character variable. Write a line of code to
//do this.
        Random rand = new Random();
        int randNum = rand.nextInt(25) + 97;
        char lowerCase = (char)randNum;
        System.out.println(lowerCase);
//(c) Suppose we have an array called a of integers want to store the average of those items in a double
//variable called b. Write a line of code to do this.
        double sum =0;
        int[] a=new int[100];
        for (int i =0; i<a.length;i++){
            sum+= (double)i;
        }
        System.out.println(sum);
//Write a program that takes a list of product names and a list of prices, applies an 11% discount to each
//of the prices, and prints the info with the product names left-justified and the discounted prices
//right-justified, like below:
//apples $ 0.93
//detergent $ 11.35
//cordless drill $ 125.35
//You can put whatever you want in your lists; just make sure your printing code can work with
//whatever lists (of whatever size) might be used. You can assume product names will be no more than
//30 characters and that prices will be under $10,000.
        List<String> products = new ArrayList<String>();
        //Collections.addAll(products, "apples","detergent","cordless drill");
        String[] names= {"apples","detergent","cordless drill"};
        double[] prices= {0.93,11.35,125.35};
        for (int i=0; i<names.length;i++){
            String name= names[i];
            double price = prices[i];
            double discount= prices[i]*.89;
            System.out.printf(name +" "+ price + " Discounted price: "+ "%.2f\n",discount);
        }
//Write a program that uses a loop to print out 1, 2, A, 3, 4, 5, B, 6, 7, A, 8, 9, 10, B, . . .
// going up to 100.
//A’s should be printed right after every number that leaves a remainder of 2 when divided by 5 (i.e. 2,
//7, 12, 17, etc.) and the B’s should be printed right after every multiple of 5.
        for (int i =0; i<100;i++){
            System.out.println(i);
            if (i%5==2){
                System.out.println("A");
            }
            if (i%5==0){
                System.out.println("B");
            }
        }
//Write a program that creates a list that contains the first 1000 positive integers that start and end with
//the same digit (like 5, 44, 262, 1231, and 7997). Note that single digit numbers by default start and
//end with the same digit. As your program is finding these numbers, after every 100th number is found
//and added to the list, print out how many numbers have been found thus far.
        int count =0;
        ArrayList<Integer> num=new ArrayList<Integer>();
        for (int i = 0; count < 1000; i++) {
            String same = String.valueOf(i);
            if (same.charAt(0) == same.charAt(same.length() - 1)) {
                num.add(i);
                count++;
                if (count % 100 == 0) {
                    System.out.println("Numbers found so far: " + count);
                }
                System.out.println(num.get(count - 1));
            }
        }
//First, ask the user to enter a string of only lowercase letters.
// Then generate a random number from 0 to 25 for each of the letters of the user’s string.
//Shift each letter by that amount, wrapping around the alphabet as needed. For instance, if the
//user enters “cap” and the random numbers generated by Java are 4, 10, and 12, then the output should
//be “gkb” (since g is 4 letters after c, k is 10 letters after a, and b is 12 letters after p
// (wrapping around).
        String f = "abcdefghijkmnopqrstuvwxyz";
        Scanner scan=new Scanner(System.in);
        System.out.println("Enter lowercase letters: ");
        String userLet=scan.nextLine();
        int randomNum1= rand.nextInt(26);
        int randomNum2= rand.nextInt(26);
        int randomNum3= rand.nextInt(26);
        System.out.println(randomNum1);
        System.out.println(randomNum2);
        System.out.println(randomNum3);
        for (int i=0; i<userLet.length();i++) {
            String newWord1 =userLet.replace(userLet.charAt(0), f.charAt(randomNum1));
            String newWord2 =newWord1.replace(newWord1.charAt(1), f.charAt(randomNum2));
            String newWord3 =newWord2.replace(newWord2.charAt(2), f.charAt(randomNum3));
            System.out.println(newWord3);

        }
        //String firstLetter = userLet.replace(userLet.charAt(0), f.charAt(randomNum));
        //System.out.println(firstLetter);

    }
}
