/*
The credit ranges are 0-23 for freshmen, 24-53 for sophomores, 54-83 for juniors, \
and 84 and over for seniors.
*/

import com.sun.source.tree.WhileLoopTree;

import java.util.Random;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("How many credits have you taken:");
        int credits = scanner.nextInt();
        if (credits >= 0 && credits <= 23)
            System.out.println("You are a Freshman.");
        else if (credits >23 && credits<=53)
            System.out.println("You are a Sophomore.");
        else if (credits>=54 && credits<=83)
            System.out.println("You are a Junior.");
        else if (credits>= 84)
            System.out.println("You are a Senior.");

        /*Ask the user to enter an integer.
        If they enter 0, print out the word “Hello” 1000 times.
        If they enter 1,ask them for another integer.
        If this new integer is 99, print out the string “?????”.
        if the first number the person entered was anything other than 1 or 2,
        print out “Goodbye”*/

        System.out.println("Enter an integer: ");
        int userNum = scanner.nextInt();
        if (userNum == 0)
            for (int i =0; i<1001; i++)
                System.out.println("Hello");
        if (userNum == 1) {
            System.out.println("Enter a new number: ");
            int newNum = scanner.nextInt();
            if (newNum == 99)
                System.out.println("?????");
        }
        if (userNum !=1 && userNum!= 2) {
            System.out.println("Goodbye");
        }
/*Ask the user for a starting hour and ending hour, both given in
24 hour format (e.g., 1 pm is 13, 2 pm is 14, etc.).
The charge to use the service is $5.50 per hour.
Print out the user’s total bill.
You can assume that the service will never be used for more than 24 hours.
Be careful to take care of the case that the starting hour is before midnight
and the ending time is after midnight.
[For example, if the starting and ending hours are 9 and 15, the total bill will be
$33.00. If the starting and ending hours are 23 and 1, the total bill will be $11.00.] */
    double charge = 5.50;
    double total = 0.0;
    System.out.println("What is the Starting Hr:");
    int startHr = scanner.nextInt();
    System.out.println("What is the ending Hr:");
    int endHr = scanner.nextInt();
        if (endHr < startHr) {
            int overHours = 24 - startHr + endHr;
            total = overHours * charge;
        } else {
            // Calculate the total bill for the hours within the same day
            int hourInday = endHr - startHr;
            total = hourInday * charge;
        }
        System.out.println("Total bill: $" + total);


        /*Write a program that allows the user to enter any number of test scores. The user indicates they are
done by entering in a negative number. Print how many of the scores are A’s (90 or above).*/
        System.out.println("Enter test scores: ");
        int countA = 0; // Initialize a count for A grades
        while (true) {
            int userNum2 = scanner.nextInt();
            if (userNum2 < 0) {
                break;
            }
            if (userNum2 >= 90) {
                System.out.println("A");
                countA++;
            }
        }
        System.out.println("Number of A's: " + countA);
        System.out.println("Done");

        /*Write a program that generates and prints 50 random zeroes and ones (generated by Java), all on the
same line, with no spaces separating them.*/
        Random random = new Random();
        for (int i = 0; i<50; i++){
            int randomBit = random.nextInt(2);
            System.out.print(randomBit);
        }

        /*or example, 3 = 2 · 1 + 1, 7 = 2 · 3 + 1, and 17 = 2 · 7 + 3.
In equation form, each term an is given by an = 2an−1 + an−2. Write a program that asks the user for a
value, n, and prints out the nth term of the sequence.*/
        System.out.println("Enter a number: ");
        int n = scanner.nextInt();
        int x = 1;
        int y = 1;
        for (int i = 0; i < n-2; i++){
            int num = y;
            y = 2*y +x;
            x = num;
        }
        System.out.println(y);


        int points = 100;
        while (points > 0 && points <200) {
            int randNum = random.nextInt(10) + 1;
            System.out.println("Wat is your guess:");
            int userGuess = scanner.nextInt();
            if (userGuess == randNum) {
                points += 100;
                System.out.println("correct");
            } else if (userGuess > randNum) {
                points -= 20;
                System.out.println("Go lower");
            } else {
                points -= 10;
                System.out.println("Go higher");
            }
            if (points > 200) {
                System.out.println("You won");
            } else {
                System.out.println("You lost");
            }
        }
    }
}